### ISSUE TITLE
Coupon Issue returns 500 Server Error due to mismatched types

### ISSUE THREAD

**Issue by Non-J** [cs350-team4/ats#34]
In models.py, the response type uses "serial_num": https://github.com/cs350-team4/ats/blob/5fc173dc5c0dcbaf6ff21b517cd1861ffbe4fbc3/backend/api/models.py#L123

But the router uses "serial_number": https://github.com/cs350-team4/ats/blob/5fc173dc5c0dcbaf6ff21b517cd1861ffbe4fbc3/backend/api/routers/coupon.py#L54

That causes 500 Internal server error:

```
backend-api-1      | INFO:     172.27.0.1:44890 - "POST /coupon/issue HTTP/1.1" 500 Internal Server Error
backend-api-1      | ERROR:    Exception in ASGI application
backend-api-1      | Traceback (most recent call last):
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
backend-api-1      |     result = await app(  # type: ignore[func-returns-value]
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-api-1      |     return await self.app(scope, receive, send)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
backend-api-1      |     await super().__call__(scope, receive, send)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
backend-api-1      |     await self.middleware_stack(scope, receive, send)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-api-1      |     raise exc
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-api-1      |     await self.app(scope, receive, _send)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
backend-api-1      |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
backend-api-1      |     await self.app(scope, receive, send)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-api-1      |     raise exc
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-api-1      |     await self.app(scope, receive, sender)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-api-1      |     raise e
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-api-1      |     await self.app(scope, receive, send)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
backend-api-1      |     await route.handle(scope, receive, send)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
backend-api-1      |     await self.app(scope, receive, send)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
backend-api-1      |     response = await func(request)
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 255, in app
backend-api-1      |     content = await serialize_response(
backend-api-1      |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 141, in serialize_response
backend-api-1      |     raise ValidationError(errors, field.type_)
backend-api-1      | pydantic.error_wrappers.ValidationError: 1 validation error for IssueCouponResponse
backend-api-1      | response -> serial_num
backend-api-1      |   field required (type=value_error.missing)
```

**Comment by m-spitfire** [comment]
Yes that's right.... Aziz fixed it recently, he'll merge soon I hope. We have changed db column from serial_num to serial_number

**Comment by m-spitfire** [comment]
sry I didn't have any motivation to use a migration lib in the beginning^^
